apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- secret.yaml

commonLabels:
  env: production

images:
- name: doll-shop-api
  newName: doll-shop-api
  newTag: production-v1.0.0
