apiVersion: v1
kind: Secret
metadata:
  name: doll-shop-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "WXaobVZ9DI" # Replace with your production password
  API_SIGNATURE_TEXT: "somesecret" # Replace with your production secret
